### ISSUE TITLE
[Feat] MatchView 의 UI 를 수정 및 위치 정보 로직을 수정합니다.

### ISSUE THREAD

**Issue by 2youngjun** [PLREQ/PLREQ#45]
## Description
- MatchView 의 UI 를 수정합니다.

## Tasks
 - [x] UICollectionViewCell ContentMode 및 ContentInset 수정
 - [x] UICollectionViewCell Background 수정
 - [x] CoreData 에 PlayList 저장 시 현재 위치 및 위도/경도 저장되도록 변경
 - [x] 음악 매칭 종료 시에만 현재 위치를 받아오고, 이를 Alert 의 TextField 에 현재 위치를 포함한 Placeholder 제공

**Comment by LeeSungNo-ian** [comment]
와아 드디어!
