### ISSUE TITLE
[Feat] 앱이 백그라운드 상태로 진입했을 때에 대한 로직을 구현합니다.

### ISSUE THREAD

**Issue by 2youngjun** [PLREQ/PLREQ#50]
## Description
- 앱이 백그라운드 상태로 진입했을 때에 대한 로직을 구현합니다.

## Tasks
- [x] 음악 매칭 버튼을 다시 클릭하였을 때 음악 매칭을 중단하도록 한다.
- [x] 음악이 매칭 중일 때 Screen 이 꺼지지 않도록 구현한다.
- [x] 앱이 백그라운드 상태로 진입했을 때, 현재 매칭되었던 PlayList 에 저장된 노래를 UserDefault 로 저장한다.
- [x] 앱이 다시 켜졌을 때 UserDefault 에 저장된 음악들을 다시 불러와 MatchView 의 UI 를 구성한다.
- [x] 위 설명처럼 MatchView 의 UI 를 구성한 다음, View 에 쌓인 음악에 대해서 이전에 유저가 추가한 Music Playlist 임을 설명하는 Alert 를 구현한다.
