### ISSUE TITLE
[Feat] 새로운 기능 제안

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [PLREQ/PLREQ#64]
## Description
- 1. 플레이리스트 검색 기능 추가
- 2. 플레이리스트 합치기 기능 추가
- 3. 서울시나 인천 같이 대도시의 경우에는 PlayList 뷰의 지역별로 보는 페이지에서 구 단위까지 나오도록 해주는 기능 추가

@yeniful 
@LeeSungNo-ian 
@2youngjun 

### TODO
- [ ] 플레이리스트 검색 기능 추가
- [ ] 플레이리스트 합치기 기능 추가
- [x] 서울시나 인천 같이 대도시의 경우에는 PlayList 뷰의 지역별로 보는 페이지에서 구 단위까지 나오도록 해주는 기능 추가
