### ISSUE TITLE
[Feat] MatchView 에서의 수정 사항을 반영하고, 음악 매칭 관련 이슈를 해결합니다

### ISSUE THREAD

**Issue by 2youngjun** [PLREQ/PLREQ#98]
## Description
- MatchView 에서의 수정 사항을 반영하고, 음악 매칭 이슈를 해결합니다.

## Tasks
 - [x] 유저의 위치를 받아오지 못한 채 음악 매칭이 종료되었을 시 저장되는 플레이리스트 이름 설정
 - [x] 30초 마다 수행되는 음악 매칭 도중에 pause 버튼을 누를 시 그대로 음악 매칭이 지속되는 이슈 수정
 - [x] 이전에 매칭되었던 음악에 대한 Alert 에서 `비우기` 버튼 스타일 cancel → destructive 로 수정
